# Generated by Django 4.0.3 on 2022-03-28 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_ap', '0002_url_franchise_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='last_scraped',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
